apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
spec:
  serviceName: nacos-headless
  replicas: {{ .Values.nacos.replicaCount }}
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
        - name: nacos
          image: "{{ .Values.nacos.image }}:{{ .Values.nacos.tag }}"
          ports:
            - containerPort: 8848
            - containerPort: 9848
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: nacos-env
          volumeMounts:
            - name: nacos-logs
              mountPath: /home/nacos/logs
          resources:
            {{- toYaml .Values.nacos.resources | nindent 12 }}
      volumes:
        - name: nacos-logs
          emptyDir: {}