apiVersion: v1
kind: Service
metadata:
  name: nacos-lb
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: internet
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: slb.s2.small
spec:
  type: LoadBalancer
  ports:
    - port: 8848
      targetPort: 8848
      name: client
    - port: 8080
      targetPort: 8080
      name: web
    - port: 9848
      targetPort: 9848
      name: rpc
  selector:
    app: nacos 